// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Interview_FollowUp_Core.Service.DataAccess;

public partial class Interview
{
    public int InterviewId { get; set; }

    public string CompanyName { get; set; }

    public string JobRole { get; set; }

    public string Location { get; set; }

    public string InterviewType { get; set; }

    public DateTime? InterviewDate { get; set; }

    public string Status { get; set; }

    public string Source { get; set; }

    public DateTime? CreatedDate { get; set; }
}