// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Interview_FollowUp_Core.Service.DataAccess;

public partial class INV_ProjectContext : DbContext
{
    public INV_ProjectContext(DbContextOptions<INV_ProjectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Interview> Interviews { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Interview>(entity =>
        {
            entity.HasKey(e => e.InterviewId);

            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.InterviewDate).HasColumnType("datetime");
            entity.Property(e => e.InterviewType).HasMaxLength(50);
            entity.Property(e => e.JobRole).HasMaxLength(150);
            entity.Property(e => e.Location).HasMaxLength(150);
            entity.Property(e => e.Source).HasMaxLength(100);
            entity.Property(e => e.Status).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}